services:
  - type: web
    name: resume-parser-python
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_KEY
        sync: false

